title: Immersive Tutorials
description: >
baseurl: "/Education-Immersive-Tutorials" # the subpath of your site, e.g. /blog
url: "cornelldatascience.github.io" # the base hostname & protocol for your site
plugin:
  - jekyll-seo-tag

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
